### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by jhandel** [garyjohnson/wpnest#1]
I am connected to Wifi, and continually get the error "Oops W had some trouble connecting with the server. Check your internet connection and tap to try again"

I have confirmed my login is correct, and uninstalled and reinstalled the app to validate that this wasn't an install issue.

**Comment by jhandel** [comment]
Pulling down the source, the issue is with the Fan being in "Duty-cycle" mode which isn't known by your current codebase... working on a patch... Will send a pull request if I figure it out.

**Comment by aaronlower** [comment]
+1, I'm having same issue, please fix.

**Comment by garyjohnson** [comment]
Fixed under https://github.com/GaryJohnson/wpnest/pull/2
